# Path to your oh-my-zsh installation.
export ZSH=~/.dotfiles/zsh/oh-my-zsh
export AZ_COMP=~/.dotfiles/az.completion
export ZSH_PLUGIN_PATH_AUTOSUGG="$ZSH/plugins/zsh-autosuggestions"
export ZSH_PLUGIN_PATH_FORGIT="$ZSH/plugins/forgit"

if [ ! -d "$ZSH" ]; then
    echo 'Cloning Oh-My-Zsh... because it is the first time you are using ZSH'
    git clone -q --depth=1 https://github.com/robbyrussell/oh-my-zsh.git "$ZSH" > /dev/null
fi

if [ ! -f "$AZ_COMP" ]; then
    wget https://raw.githubusercontent.com/Azure/azure-cli/dev/az.completion -O "$AZ_COMP"
fi

if [ ! -d "$ZSH_PLUGIN_PATH_AUTOSUGG" ]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_PLUGIN_PATH_AUTOSUGG} > /dev/null
fi

if [ ! -d "$ZSH_PLUGIN_PATH_FORGIT" ]; then
    mkdir ${ZSH_PLUGIN_PATH_FORGIT}
    curl -Ss https://raw.githubusercontent.com/wfxr/forgit/master/forgit.plugin.zsh -o ${ZSH_PLUGIN_PATH_FORGIT}/forgit.plugin.zsh
fi

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="gnzh"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git command-not-found gpg-agent tmux autojump docker docker-compose postgres redis-cli composer archlinux systemd sudo supervisor history cp adb ant bower bundler npm node man pip python ruby rvm rust z symfony symfony2 kubectl cargo git-extras fzf aws minikube terraform zsh-autosuggestions forgit)

# User configuration

if [ -f ~/.zsh_local ]; then
    source ~/.zsh_local
fi

source $ZSH/oh-my-zsh.sh

bindkey '^i' expand-or-complete-prefix

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

export EDITOR=nano
alias e=$EDITOR

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

autoload -U +X bashcompinit && bashcompinit

# load azure cli auto-completion
source "$AZ_COMP"

# load forgit plugin
#source ${ZSH_PLUGIN_PATH_FORGIT}/forgit.plugin.zsh

# add Pulumi to the PATH
export PATH=$PATH:$HOME/.pulumi/bin

alias ls=exa
